"""
etl_ptbxl_v2.py

ETL: PTB-XL metadata (ptbxl_database.csv) -> OMOP CDM 5.x, driven by
dqd/mapping/mapping_ptbxl-ecg-records.json (see generate_ptbxl_mapping.py).

This is the mapping-informed version, replacing the earlier hand-coded
etl_ptbxl.py. Table targets (person / measurement / observation / note /
condition_occurrence) and value_field choices below follow that mapping
file's decisions, with two deliberate deviations documented inline:

  1. ecg_id and recording_date were mapped to their own standalone
     measurement rows in the LLM output, but neither is really a
     "value" in its own right -- ecg_id is a record identifier and
     recording_date is shared context for every other row generated
     from that record. Rather than create meaningless placeholder rows
     for them, recording_date is applied as the date/datetime on every
     row generated from that ECG record, and ecg_id is not separately
     stored (person_id + dates + source_value already trace back to
     the source row well enough for this dataset's purposes).

  2. Binary/flag variables (second_opinion, validated_by_human,
     baseline_drift, etc.) were mapped by the LLM to value_as_concept_id
     using Yes/No concepts (38003565/38003564) it recalled but could
     not verify against a real vocabulary (concept table is currently
     just the bootstrap placeholder set -- see bootstrap_concept.sql).
     Rather than insert unverified concept IDs, this script stores
     these as value_as_string ("Yes"/"No") instead. Revisit once the
     real OHDSI vocabulary is loaded and those IDs are confirmed.

Confirmed against your actual DB schema via docker exec psql:
  person / condition_occurrence / measurement / observation / note
  all confirmed NOT NULL on their *_concept_id / *_date / *_type_concept_id
  columns as noted per table below.

KNOWN DATA QUALITY GAPS -- read before running DQD (same as v1):
  1. year_of_birth: not derivable from PTB-XL's de-identified
     recording_date + age. Left as 9999 sentinel; use the age
     measurement rows instead for real age data.
  2. scp_codes likelihood values are not stored, only presence of each
     statement (condition_source_value = statement code).
  3. Ages >89 are the ~300 HIPAA sentinel range, flagged via
     value_source_value on the age measurement row.
  4. condition_concept_id / measurement_concept_id / observation_concept_id
     are 0 (unmapped) throughout -- the mapping file's concept_id
     suggestions were mostly null (LLM correctly declined to guess),
     and the ones it did suggest are unverified against a real
     vocabulary that isn't loaded yet.
"""

import ast
import json
from datetime import date

import pandas as pd
import psycopg2

DATABASE_CSV = "ptbxl_database.csv"
MAPPING_FILE = "dqd/mapping/mapping_ptbxl-ecg-records.json"

UNMAPPED_CONCEPT_ID = 0
YEAR_OF_BIRTH_SENTINEL = 9999
SEX_TO_GENDER_CONCEPT = {0: 8507, 1: 8532}  # matches bootstrap_concept.sql
SEX_LABELS = {0: "Male", 1: "Female"}

DB_CONFIG = {
    "host": "localhost",
    "port": 5433,
    "dbname": "omop",
    "user": "omop_user",
    "password": "omop_pass",
}

# Binary/flag columns handled as value_as_string (see deviation #2 above)
BINARY_FLAG_FIELDS = [
    "second_opinion", "initial_autogenerated_report", "validated_by_human",
    "baseline_drift", "static_noise", "burst_noise",
    "electrodes_problems", "pacemaker",
]

# Source-value-only observation fields (pseudonymized identifiers, per
# mapping's "N/A" value_field guidance)
SOURCE_VALUE_ONLY_FIELDS = ["nurse", "site", "device", "validated_by"]

# Free-text-as-string observation fields
STRING_OBSERVATION_FIELDS = ["heart_axis", "infarction_stadium1", "infarction_stadium2", "strat_fold"]


def load_mapping():
    """Load the mapping file mainly to fail loudly if it's missing --
    the actual row-building logic below implements its decisions
    directly rather than interpreting the JSON generically, since a
    handful of fields (recording_date, ecg_id, the binary flags) need
    special-case handling the flat mapping schema can't express."""
    with open(MAPPING_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def parse_scp_codes(raw):
    if pd.isna(raw):
        return {}
    try:
        parsed = ast.literal_eval(raw)
        return parsed if isinstance(parsed, dict) else {}
    except (ValueError, SyntaxError):
        return {}


def parse_date(raw):
    if pd.isna(raw):
        return None
    try:
        return pd.to_datetime(raw).date()
    except (ValueError, TypeError):
        return None


def safe_float(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return None


def get_next_id_start(conn, table, id_column):
    with conn.cursor() as cur:
        cur.execute(f"SELECT COALESCE(MAX({id_column}), 0) FROM {table}")
        return cur.fetchone()[0] + 1


# --- Row builders -----------------------------------------------------

def build_person_rows(db, id_start):
    rows = []
    next_id = id_start
    patient_to_person_id = {}

    for patient_id, group in db.groupby("patient_id"):
        sex_val = group["sex"].dropna().iloc[0] if group["sex"].notna().any() else None
        gender_concept_id = SEX_TO_GENDER_CONCEPT.get(sex_val, UNMAPPED_CONCEPT_ID)
        gender_source_value = SEX_LABELS.get(sex_val) if sex_val is not None else None

        rows.append({
            "person_id": next_id,
            "gender_concept_id": gender_concept_id,
            "year_of_birth": YEAR_OF_BIRTH_SENTINEL,
            "race_concept_id": UNMAPPED_CONCEPT_ID,
            "ethnicity_concept_id": UNMAPPED_CONCEPT_ID,
            "person_source_value": str(int(patient_id)),
            "gender_source_value": gender_source_value,
        })
        patient_to_person_id[patient_id] = next_id
        next_id += 1

    return rows, patient_to_person_id


def build_measurement_rows(db, patient_to_person_id, id_start):
    """age, height, weight, extra_beats -> value_as_number, per mapping."""
    rows = []
    next_id = id_start
    skipped_malformed = 0

    fields = [("height", "cm"), ("weight", "kg"), ("extra_beats", None), ("age", "years")]

    for ecg_id, record in db.iterrows():
        person_id = patient_to_person_id[record["patient_id"]]
        record_date = parse_date(record.get("recording_date")) or date(1970, 1, 1)

        for field, unit in fields:
            raw_value = record.get(field)
            if pd.isna(raw_value):
                continue
            value = safe_float(raw_value)
            if value is None:
                skipped_malformed += 1
                continue

            value_source_note = None
            if field == "age" and value > 89:
                value_source_note = "age>89 (HIPAA de-id sentinel)"  # kept under varchar(50)

            rows.append({
                "measurement_id": next_id,
                "person_id": person_id,
                "measurement_concept_id": UNMAPPED_CONCEPT_ID,
                "measurement_date": record_date,
                "measurement_type_concept_id": UNMAPPED_CONCEPT_ID,
                "value_as_number": value,
                "unit_source_value": unit,
                "measurement_source_value": field,
                "value_source_value": value_source_note,
            })
            next_id += 1

    if skipped_malformed:
        print(f"  WARNING: skipped {skipped_malformed} malformed non-numeric "
              f"values (source data quality issue, not an ETL bug).")

    return rows


def build_observation_rows(db, patient_to_person_id, id_start):
    """nurse/site/device/validated_by (source-value-only), heart_axis/
    infarction_stadium1/2/strat_fold (value_as_string), and the binary
    flag fields (also value_as_string per deviation #2)."""
    rows = []
    next_id = id_start

    for ecg_id, record in db.iterrows():
        person_id = patient_to_person_id[record["patient_id"]]
        record_date = parse_date(record.get("recording_date")) or date(1970, 1, 1)

        for field in SOURCE_VALUE_ONLY_FIELDS:
            raw_value = record.get(field)
            if pd.isna(raw_value):
                continue
            rows.append({
                "observation_id": next_id,
                "person_id": person_id,
                "observation_concept_id": UNMAPPED_CONCEPT_ID,
                "observation_date": record_date,
                "observation_type_concept_id": UNMAPPED_CONCEPT_ID,
                "value_as_number": None,
                "value_as_string": None,
                "observation_source_value": f"{field}:{raw_value}",
            })
            next_id += 1

        for field in STRING_OBSERVATION_FIELDS:
            raw_value = record.get(field)
            if pd.isna(raw_value):
                continue
            rows.append({
                "observation_id": next_id,
                "person_id": person_id,
                "observation_concept_id": UNMAPPED_CONCEPT_ID,
                "observation_date": record_date,
                "observation_type_concept_id": UNMAPPED_CONCEPT_ID,
                "value_as_number": None,
                "value_as_string": str(raw_value),
                "observation_source_value": field,
            })
            next_id += 1

        for field in BINARY_FLAG_FIELDS:
            raw_value = record.get(field)
            if pd.isna(raw_value):
                continue
            # See deviation #2 in module docstring -- string, not
            # value_as_concept_id, until real Yes/No concepts are
            # verified against a loaded vocabulary.
            flag_str = "Yes" if raw_value else "No"
            rows.append({
                "observation_id": next_id,
                "person_id": person_id,
                "observation_concept_id": UNMAPPED_CONCEPT_ID,
                "observation_date": record_date,
                "observation_type_concept_id": UNMAPPED_CONCEPT_ID,
                "value_as_number": None,
                "value_as_string": flag_str,
                "observation_source_value": field,
            })
            next_id += 1

    return rows


def build_condition_rows(db, patient_to_person_id, id_start):
    """scp_codes -> one condition_occurrence row per SCP-ECG statement."""
    rows = []
    next_id = id_start

    for ecg_id, record in db.iterrows():
        person_id = patient_to_person_id[record["patient_id"]]
        record_date = parse_date(record.get("recording_date")) or date(1970, 1, 1)
        statements = parse_scp_codes(record.get("scp_codes"))

        for statement_code in statements:
            rows.append({
                "condition_occurrence_id": next_id,
                "person_id": person_id,
                "condition_concept_id": UNMAPPED_CONCEPT_ID,
                "condition_start_date": record_date,
                "condition_type_concept_id": UNMAPPED_CONCEPT_ID,
                "condition_source_value": statement_code,
            })
            next_id += 1

    return rows


def build_note_rows(db, patient_to_person_id, id_start):
    """report -> note.note_text, per mapping."""
    rows = []
    next_id = id_start

    for ecg_id, record in db.iterrows():
        raw_value = record.get("report")
        if pd.isna(raw_value):
            continue

        person_id = patient_to_person_id[record["patient_id"]]
        record_date = parse_date(record.get("recording_date")) or date(1970, 1, 1)

        rows.append({
            "note_id": next_id,
            "person_id": person_id,
            "note_date": record_date,
            "note_type_concept_id": UNMAPPED_CONCEPT_ID,
            "note_class_concept_id": UNMAPPED_CONCEPT_ID,
            "note_text": str(raw_value),
            "encoding_concept_id": UNMAPPED_CONCEPT_ID,
            "language_concept_id": UNMAPPED_CONCEPT_ID,
            "note_source_value": "report",
        })
        next_id += 1

    return rows


# --- Insert functions ---------------------------------------------------

def insert_persons(conn, rows):
    with conn.cursor() as cur:
        for r in rows:
            cur.execute(
                """
                INSERT INTO person (
                    person_id, gender_concept_id, year_of_birth,
                    race_concept_id, ethnicity_concept_id,
                    person_source_value, gender_source_value
                ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (person_id) DO NOTHING
                """,
                (r["person_id"], r["gender_concept_id"], r["year_of_birth"],
                 r["race_concept_id"], r["ethnicity_concept_id"],
                 r["person_source_value"], r["gender_source_value"]),
            )
    conn.commit()


def insert_measurements(conn, rows):
    with conn.cursor() as cur:
        for r in rows:
            cur.execute(
                """
                INSERT INTO measurement (
                    measurement_id, person_id, measurement_concept_id,
                    measurement_date, measurement_type_concept_id,
                    value_as_number, unit_source_value,
                    measurement_source_value, value_source_value
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (r["measurement_id"], r["person_id"], r["measurement_concept_id"],
                 r["measurement_date"], r["measurement_type_concept_id"],
                 r["value_as_number"], r["unit_source_value"],
                 r["measurement_source_value"], r["value_source_value"]),
            )
    conn.commit()


def insert_observations(conn, rows):
    with conn.cursor() as cur:
        for r in rows:
            cur.execute(
                """
                INSERT INTO observation (
                    observation_id, person_id, observation_concept_id,
                    observation_date, observation_type_concept_id,
                    value_as_number, value_as_string, observation_source_value
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (r["observation_id"], r["person_id"], r["observation_concept_id"],
                 r["observation_date"], r["observation_type_concept_id"],
                 r["value_as_number"], r["value_as_string"], r["observation_source_value"]),
            )
    conn.commit()


def insert_conditions(conn, rows):
    with conn.cursor() as cur:
        for r in rows:
            cur.execute(
                """
                INSERT INTO condition_occurrence (
                    condition_occurrence_id, person_id, condition_concept_id,
                    condition_start_date, condition_type_concept_id,
                    condition_source_value
                ) VALUES (%s, %s, %s, %s, %s, %s)
                """,
                (r["condition_occurrence_id"], r["person_id"], r["condition_concept_id"],
                 r["condition_start_date"], r["condition_type_concept_id"],
                 r["condition_source_value"]),
            )
    conn.commit()


def insert_notes(conn, rows):
    with conn.cursor() as cur:
        for r in rows:
            cur.execute(
                """
                INSERT INTO note (
                    note_id, person_id, note_date, note_type_concept_id,
                    note_class_concept_id, note_text, encoding_concept_id,
                    language_concept_id, note_source_value
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (r["note_id"], r["person_id"], r["note_date"], r["note_type_concept_id"],
                 r["note_class_concept_id"], r["note_text"], r["encoding_concept_id"],
                 r["language_concept_id"], r["note_source_value"]),
            )
    conn.commit()


def main():
    load_mapping()  # fail loudly if missing/malformed
    print("Loading ptbxl_database.csv ...")
    db = pd.read_csv(DATABASE_CSV, index_col="ecg_id")
    print(f"{len(db)} records, {db['patient_id'].nunique()} patients.")

    conn = psycopg2.connect(**DB_CONFIG)

    person_id_start = get_next_id_start(conn, "person", "person_id")
    measurement_id_start = get_next_id_start(conn, "measurement", "measurement_id")
    observation_id_start = get_next_id_start(conn, "observation", "observation_id")
    condition_id_start = get_next_id_start(conn, "condition_occurrence", "condition_occurrence_id")
    note_id_start = get_next_id_start(conn, "note", "note_id")

    print("Building rows...")
    person_rows, patient_to_person_id = build_person_rows(db, person_id_start)
    measurement_rows = build_measurement_rows(db, patient_to_person_id, measurement_id_start)
    observation_rows = build_observation_rows(db, patient_to_person_id, observation_id_start)
    condition_rows = build_condition_rows(db, patient_to_person_id, condition_id_start)
    note_rows = build_note_rows(db, patient_to_person_id, note_id_start)

    print(f"  {len(person_rows)} person rows")
    print(f"  {len(measurement_rows)} measurement rows")
    print(f"  {len(observation_rows)} observation rows")
    print(f"  {len(condition_rows)} condition rows")
    print(f"  {len(note_rows)} note rows")

    print("\nInserting into OMOP CDM...")
    insert_persons(conn, person_rows)
    insert_measurements(conn, measurement_rows)
    insert_observations(conn, observation_rows)
    insert_conditions(conn, condition_rows)
    insert_notes(conn, note_rows)

    conn.close()
    print("\nDone.")


if __name__ == "__main__":
    main()
