"""
extractor_ptbxl.py

Builds a schema.json-style catalog entry for PTB-XL directly from
ptbxl_database.csv and scp_statements.csv (both freely downloadable,
no PhysioNet credentialed access required -- CC BY 4.0).

Unlike TCGA/NHANES, PTB-XL is not naturally split into many per-dataset
entries -- it's a single flat CSV of 21799 ECG records from 18869
patients. This script produces ONE catalog entry summarizing the
dataset, plus prints the field breakdown you'll want for the follow-up
ETL script (etl_ptbxl.py).

Files this script expects (auto-downloaded if not present locally):
  ptbxl_database.csv   -- one row per ECG record, 28 columns
  scp_statements.csv   -- SCP-ECG statement lookup / hierarchy

Data source: https://physionet.org/content/ptb-xl/1.0.3/
"""

import json
import os
from datetime import date

import pandas as pd
import requests

BASE_URL = "https://physionet.org/files/ptb-xl/1.0.3/"
DATABASE_CSV = "ptbxl_database.csv"
SCP_STATEMENTS_CSV = "scp_statements.csv"

# PTB-XL is ECG data. The app's subtype taxonomy (see SUBTYPE_TAG in
# data.js) uses flat, lowercase, hyphenated leaf keys -- not top-level
# category names. "ecg" is the correct and only tag for this dataset;
# there is no separate "tabular" or "multi-modal" key in that taxonomy.
SUBTYPES = ["ecg"]

# Static documentation for each ptbxl_database.csv column, matching the
# schema.json "variables" shape used by NHANES entries (name/label/
# english_text/target/count/values/data_type/unit/notes). count/values
# are filled in at runtime from the actual data where useful.
COLUMN_DOCS = {
    "ecg_id": ("Record ID", "Unique identifier for each ECG record.", "Identifier", None),
    "patient_id": ("Patient ID", "Unique identifier for the patient; a patient may have multiple ECG records.", "Identifier", None),
    "age": ("Age", "Age of the patient at time of recording. Ages >89 are encoded in the ~300 range for HIPAA de-identification.", "Continuous", "years"),
    "sex": ("Sex", "Patient sex.", "Categorical", None),
    "height": ("Height", "Patient height, if recorded.", "Continuous", "cm"),
    "weight": ("Weight", "Patient weight, if recorded.", "Continuous", "kg"),
    "nurse": ("Recording Nurse (pseudonymized)", "Pseudonymized identifier of the nurse who performed the recording.", "Categorical", None),
    "site": ("Recording Site (pseudonymized)", "Pseudonymized identifier of the recording site/hospital.", "Categorical", None),
    "device": ("ECG Device", "Recording device model used.", "Categorical", None),
    "recording_date": ("Recording Date", "Date of the ECG recording, shifted by a random per-patient offset for de-identification.", "Text", None),
    "report": ("Report String", "Free-text report generated by cardiologist or automatic ECG-device interpretation.", "Text", None),
    "scp_codes": ("SCP-ECG Statements", "Dictionary of SCP-ECG diagnostic statements with likelihoods (0 = unknown likelihood).", "Text", None),
    "heart_axis": ("Heart Axis", "Extracted cardiac electrical axis, where available.", "Categorical", None),
    "infarction_stadium1": ("Infarction Stadium (primary)", "Infarction staging, if applicable.", "Categorical", None),
    "infarction_stadium2": ("Infarction Stadium (secondary)", "Secondary infarction staging, if applicable.", "Categorical", None),
    "validated_by": ("Validating Cardiologist (pseudonymized)", "Pseudonymized identifier of the validating cardiologist.", "Categorical", None),
    "second_opinion": ("Second Opinion Given", "Whether a second cardiologist reviewed the record.", "Binary", None),
    "initial_autogenerated_report": ("Auto-generated Report Flag", "Whether the initial report was auto-generated by the ECG device.", "Binary", None),
    "validated_by_human": ("Human-Validated Flag", "Whether the record was validated by a human cardiologist.", "Binary", None),
    "baseline_drift": ("Baseline Drift", "Signal quality flag for baseline drift artifacts.", "Categorical", None),
    "static_noise": ("Static Noise", "Signal quality flag for static noise artifacts.", "Categorical", None),
    "burst_noise": ("Burst Noise", "Signal quality flag for burst noise artifacts.", "Categorical", None),
    "electrodes_problems": ("Electrode Problems", "Signal quality flag for electrode placement/contact issues.", "Categorical", None),
    "extra_beats": ("Extra Beats Count", "Count of extra systoles (ectopic beats) detected, if any.", "Continuous", None),
    "pacemaker": ("Pacemaker Signal Pattern", "Flag for signal patterns indicating an active pacemaker.", "Categorical", None),
    "strat_fold": ("Stratified CV Fold", "Recommended 10-fold train/test split (1-8 train, 9 validation, 10 test), stratified so all records of a patient share a fold.", "Categorical", None),
    "filename_lr": ("Waveform Path (100Hz)", "Relative path to the downsampled 100Hz waveform file.", "Identifier", None),
    "filename_hr": ("Waveform Path (500Hz)", "Relative path to the original 500Hz waveform file.", "Identifier", None),
}


def build_variable_entry(col, series):
    """Build one NHANES-style variable entry for a ptbxl_database.csv
    column, using COLUMN_DOCS for the static description and the actual
    data for count/values where the column is low-cardinality."""
    label, english_text, data_type, unit = COLUMN_DOCS.get(
        col, (col, "See PTB-XL documentation.", "Text", None)
    )

    non_null_count = int(series.notna().sum())
    values = []

    # For low-cardinality columns, include a code/desc/count breakdown
    # like NHANES does. High-cardinality or free-text columns are left
    # with an empty values list -- browsing every unique report string
    # isn't useful the way browsing "Male/Female" counts is.
    nunique = series.nunique(dropna=True)
    if data_type in ("Categorical", "Binary") and nunique <= 15:
        counts = series.value_counts(dropna=False)
        for code, count in counts.items():
            code_str = "." if pd.isna(code) else str(code)
            values.append({"code": code_str, "desc": str(code) if not pd.isna(code) else "Missing", "count": int(count)})

    return {
        "name": col,
        "label": label,
        "english_text": english_text,
        "target": None,
        "count": non_null_count,
        "values": values,
        "data_type": data_type,
        "unit": unit,
        "notes": None,
    }


def download_if_missing(filename):
    if os.path.exists(filename):
        return filename
    url = BASE_URL + filename
    print(f"Downloading {filename} from {url} ...")
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    with open(filename, "wb") as f:
        f.write(resp.content)
    return filename


def build_schema_entry():
    download_if_missing(DATABASE_CSV)
    download_if_missing(SCP_STATEMENTS_CSV)

    db = pd.read_csv(DATABASE_CSV, index_col="ecg_id")
    scp = pd.read_csv(SCP_STATEMENTS_CSV, index_col=0)

    record_count = len(db)
    patient_count = db["patient_id"].nunique()

    # PTB-XL encodes ages >89 in the ~300 range for HIPAA de-identification
    # (see dataset docs). Report the real clinical range separately from
    # the de-identified sentinel range so the catalog description doesn't
    # show a nonsensical "age 2-300".
    normal_ages = db.loc[db["age"] <= 89, "age"]
    obfuscated_count = int((db["age"] > 89).sum())
    age_min, age_max = normal_ages.min(), normal_ages.max()

    male_pct = round((db["sex"] == 0).mean() * 100, 1) if db["sex"].dtype != object else None
    diagnostic_statement_count = len(scp)

    today = date.today().isoformat()

    age_note = (
        f"ages {age_min:.0f}-{age_max:.0f}"
        + (
            f" ({obfuscated_count} records de-identified as age >89, "
            f"encoded in the ~300 range per HIPAA convention -- excluded "
            f"from this range)"
            if obfuscated_count
            else ""
        )
    )

    entry = {
        "PTBXL_ecg_records": {
            "name": "PTB-XL: Large Publicly Available Electrocardiography Dataset",
            "desc": (
                f"{record_count} clinical 12-lead ECG records (10s each) from "
                f"{patient_count} patients, {age_note}. "
                f"Annotated with up to two cardiologists' SCP-ECG statements "
                f"({diagnostic_statement_count} distinct statements) covering "
                f"diagnostic, form, and rhythm categories. Waveforms at 500Hz "
                f"(records500/) and downsampled 100Hz (records100/), WFDB "
                f"format. Metadata (ptbxl_database.csv) is ETL-eligible; "
                f"waveform files are catalog-only."
            ),
            "source": "PTB-XL",
            "subtypes": SUBTYPES,
            "tasks": [],
            "last_updated": today,
            "url": "https://physionet.org/content/ptb-xl/1.0.3/",
            "etl_status": "etl_eligible",
            "record_count": int(record_count),
            "patient_count": int(patient_count),
            "age_obfuscated_gt_89_count": obfuscated_count,
            "diagnostic_superclasses": ["NORM", "MI", "STTC", "CD", "HYP"],
            "raw_data_format": "WFDB (.dat/.hea), catalog-only",
            "metadata_format": "CSV, ETL-eligible",
            "variable_count": len(db.columns) + 1,  # +1 for ecg_id, which is the index
            "variables": (
                [build_variable_entry("ecg_id", db.index.to_series())]
                + [build_variable_entry(col, db[col]) for col in db.columns]
            ),
        }
    }
    return entry


def print_field_summary():
    """Print the ptbxl_database.csv column list, useful for planning
    the follow-up etl_ptbxl.py OMOP mapping."""
    db = pd.read_csv(DATABASE_CSV, index_col="ecg_id", nrows=5)
    print("\nptbxl_database.csv columns (for OMOP mapping planning):")
    for col in db.columns:
        print(f"  {col}")


def main():
    entry = build_schema_entry()
    with open("schema_ptbxl.json", "w", encoding="utf-8") as f:
        json.dump(entry, f, indent=2, ensure_ascii=False)
    print("Wrote schema_ptbxl.json with 1 catalog entry.")
    print(json.dumps(entry, indent=2, ensure_ascii=False))
    print_field_summary()


if __name__ == "__main__":
    main()
