"""
generate_ptbxl_mapping.py

Generates dqd/mapping/mapping_ptbxl-ecg-records.json for PTB-XL, using
the same LLM-driven approach as your NHANES mapping pipeline (NIM API,
openai/gpt-oss-20b reasoning model).

Output schema matches your existing NHANES mapping files exactly:
    [{"ptbxl_var": ..., "omop_table": ..., "omop_field": ...,
      "concept_id": ..., "notes": ...}, ...]

Reads NIM_API_KEY / NIM_MODEL / NIM_BASE_URL from .env, same as your
other extractors. Since the model is a reasoning model, content comes
back in reasoning_content (not content), and the JSON array is
extracted from it via rfind -- same convention as your safe_json()
helper in extractor.py.
"""

import json
import os
import time

import requests
from dotenv import load_dotenv

load_dotenv()

NIM_API_KEY = os.environ["NIM_API_KEY"]
NIM_MODEL = os.environ.get("NIM_MODEL", "openai/gpt-oss-20b")
NIM_BASE_URL = os.environ.get("NIM_BASE_URL", "https://integrate.api.nvidia.com/v1")

MAX_RETRIES = 5
BASE_BACKOFF_SECONDS = 2

# ---------------------------------------------------------------------------
# System prompt — matches the style of your existing SYSTEM_ENRICH /
# SYSTEM_LAST_UPDATED / SYSTEM_CARD_INFO prompts.
# ---------------------------------------------------------------------------

SYSTEM_OMOP_MAPPING = """You are a biomedical data engineer specializing in the OMOP Common Data Model.
Your job is to map source dataset variables to OMOP CDM 5.x tables and fields.
You always return a valid JSON array — same length and order as the input.
Never add markdown fences, never add explanation, never skip variables.
You always distinguish between the concept that IDENTIFIES what is being
recorded and the field that HOLDS the actual value -- a variable's
mapping is incomplete without both."""

# Reused from extractor_ptbxl.py's COLUMN_DOCS -- keeps the variable
# descriptions fed to the LLM consistent with what's already in
# schema.json, rather than re-deriving them.
PTBXL_VARIABLES = [
    ("ecg_id", "Record ID", "Unique identifier for each ECG record.", "Identifier"),
    ("patient_id", "Patient ID", "Unique identifier for the patient; a patient may have multiple ECG records.", "Identifier"),
    ("age", "Age", "Age of the patient at time of recording, in years. Ages >89 are encoded in the ~300 range for HIPAA de-identification.", "Continuous"),
    ("sex", "Sex", "Patient sex: 0 = male, 1 = female.", "Categorical"),
    ("height", "Height", "Patient height in cm, if recorded.", "Continuous"),
    ("weight", "Weight", "Patient weight in kg, if recorded.", "Continuous"),
    ("nurse", "Recording Nurse (pseudonymized)", "Pseudonymized identifier of the nurse who performed the recording.", "Categorical"),
    ("site", "Recording Site (pseudonymized)", "Pseudonymized identifier of the recording site/hospital.", "Categorical"),
    ("device", "ECG Device", "Recording device model used.", "Categorical"),
    ("recording_date", "Recording Date", "Date of the ECG recording, shifted by a random per-patient offset for de-identification.", "Date"),
    ("report", "Report String", "Free-text report generated by cardiologist or automatic ECG-device interpretation.", "Text"),
    ("scp_codes", "SCP-ECG Statements", "Dictionary of SCP-ECG diagnostic statements with likelihoods, e.g. {'NORM': 100.0, 'SR': 0.0}. Statements conform to the SCP-ECG standard and cover diagnostic, form, and rhythm categories (71 distinct statements total).", "Text (dict-of-codes)"),
    ("heart_axis", "Heart Axis", "Extracted cardiac electrical axis, where available.", "Categorical"),
    ("infarction_stadium1", "Infarction Stadium (primary)", "Infarction staging, if applicable.", "Categorical"),
    ("infarction_stadium2", "Infarction Stadium (secondary)", "Secondary infarction staging, if applicable.", "Categorical"),
    ("validated_by", "Validating Cardiologist (pseudonymized)", "Pseudonymized identifier of the validating cardiologist.", "Categorical"),
    ("second_opinion", "Second Opinion Given", "Whether a second cardiologist reviewed the record.", "Binary"),
    ("initial_autogenerated_report", "Auto-generated Report Flag", "Whether the initial report was auto-generated by the ECG device.", "Binary"),
    ("validated_by_human", "Human-Validated Flag", "Whether the record was validated by a human cardiologist.", "Binary"),
    ("baseline_drift", "Baseline Drift", "Signal quality flag for baseline drift artifacts.", "Categorical"),
    ("static_noise", "Static Noise", "Signal quality flag for static noise artifacts.", "Categorical"),
    ("burst_noise", "Burst Noise", "Signal quality flag for burst noise artifacts.", "Categorical"),
    ("electrodes_problems", "Electrode Problems", "Signal quality flag for electrode placement/contact issues.", "Categorical"),
    ("extra_beats", "Extra Beats Count", "Count of extra systoles (ectopic beats) detected, if any.", "Continuous"),
    ("pacemaker", "Pacemaker Signal Pattern", "Flag for signal patterns indicating an active pacemaker.", "Categorical"),
    ("strat_fold", "Stratified CV Fold", "Recommended 10-fold train/test split (1-8 train, 9 validation, 10 test).", "Categorical"),
    ("filename_lr", "Waveform Path (100Hz)", "Relative path to the downsampled 100Hz WFDB waveform file. Not ETL-eligible -- catalog reference only.", "Identifier"),
    ("filename_hr", "Waveform Path (500Hz)", "Relative path to the original 500Hz WFDB waveform file. Not ETL-eligible -- catalog reference only.", "Identifier"),
]


def build_prompt():
    var_lines = "\n".join(
        f"- {name} ({data_type}): {label}. {desc}"
        for name, label, desc, data_type in PTBXL_VARIABLES
    )
    return f"""Map each PTB-XL ECG dataset variable (from ptbxl_database.csv) below to the OMOP CDM 5.x schema.

For EACH variable, output one JSON object with these exact keys:
- "ptbxl_var": the variable name, exactly as given
- "omop_table": the OMOP CDM table this variable belongs in (e.g. person, condition_occurrence, measurement, observation, note)
- "omop_field": the concept-identifying field for this variable (e.g. observation_concept_id, measurement_concept_id, condition_concept_id) -- this says WHAT is being recorded
- "value_field": the field that holds the ACTUAL value for this variable (e.g. value_as_number, value_as_string, value_as_concept_id, value_as_datetime). Use "N/A" only for fields that are themselves identifiers/keys with no separate value (e.g. person_id, ecg_id used as a source value).
- "concept_id": a standard OMOP concept_id for the omop_field above, if you know one with confidence, otherwise null. Do not guess a plausible-looking number -- use null if uncertain.
- "concept_id_depends_on_value": true if the correct concept_id varies depending on this variable's actual row value (e.g. a sex column where male vs female need different concept_ids), false if concept_id is a fixed constant for every row of this variable. When true, explain the value->concept_id mapping in "notes" instead of picking one concept_id.
- "notes": a short note explaining the mapping choice, including any caveats

Special guidance:
- Numeric variables (age, height, weight, extra_beats) need value_field = "value_as_number".
- scp_codes is a dictionary of MULTIPLE diagnostic statements per record (e.g. {{'NORM': 100.0, 'MI': 80.0}}), not a single value. Map it to condition_occurrence with one row generated per statement key at ETL time, condition_source_value holding the statement code -- explain this multi-row pattern in "notes" rather than treating it as one flat field.
- Binary/flag variables (second_opinion, validated_by_human, initial_autogenerated_report, pacemaker, baseline_drift, static_noise, burst_noise, electrodes_problems) should specify whether they map to value_as_concept_id (if a Yes/No standard concept applies) or value_as_string (if not).
- Pseudonymized identifier variables (nurse, site, validated_by) are categorical source identifiers, not clinical concepts -- map to *_source_value fields, value_field = "N/A".

Variables to map:
{var_lines}"""


def safe_json_array(text):
    """Extract a JSON array from model output, tolerating extra text
    around it. Mirrors the rfind-based extraction convention used in
    your extractor.py's safe_json() for reasoning-model output."""
    start = text.find("[")
    end = text.rfind("]")
    if start == -1 or end == -1 or end < start:
        raise ValueError(f"No JSON array found in model output:\n{text[:500]}")
    return json.loads(text[start:end + 1])


def call_nim(prompt):
    """Call the NIM chat completions endpoint with exponential backoff
    on rate limiting, matching your existing extractor.py convention."""
    url = f"{NIM_BASE_URL}/chat/completions"
    headers = {
        "Authorization": f"Bearer {NIM_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": NIM_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_OMOP_MAPPING},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.1,
    }

    for attempt in range(MAX_RETRIES):
        resp = requests.post(url, headers=headers, json=payload, timeout=120)
        if resp.status_code == 429:
            wait = BASE_BACKOFF_SECONDS * (2 ** attempt)
            print(f"  Rate limited, retrying in {wait}s (attempt {attempt + 1}/{MAX_RETRIES})...")
            time.sleep(wait)
            continue
        resp.raise_for_status()
        return resp.json()

    raise RuntimeError("NIM API rate limit retries exhausted.")


def main():
    prompt = build_prompt()
    print(f"Requesting mapping for {len(PTBXL_VARIABLES)} PTB-XL variables from NIM ({NIM_MODEL})...")

    response = call_nim(prompt)
    message = response["choices"][0]["message"]

    # Reasoning models (like gpt-oss-20b) return the actual answer in
    # reasoning_content, with content often null/empty -- same
    # extraction pattern as your NHANES pipeline.
    raw_text = message.get("content") or message.get("reasoning_content") or ""
    if not raw_text:
        raise ValueError(f"Empty response from model. Full message: {message}")

    mapping = safe_json_array(raw_text)
    print(f"Parsed {len(mapping)} mapping entries.")

    os.makedirs("dqd/mapping", exist_ok=True)
    out_path = "dqd/mapping/mapping_ptbxl-ecg-records.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(mapping, f, indent=2, ensure_ascii=False)

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
