"""
regenerate_datajs.py

Regenerates data.js from schema.json, preserving:
  - the SUBTYPE_TAG block below the DATASETS array
  - MIMIC-IV's entries, which deliberately have NO schema.json entry
    (they're restricted-access, so no variable schema was ever
    extracted for them -- see schema.html's 'restricted' handling) and
    would otherwise be silently dropped by a naive schema.json-only
    rebuild
  - every entry's existing 'linkage' field, which lives only in
    data.js (generated by generate_nhanes_linkage.py for NHANES and
    hand-written for MIMIC-IV) and has no equivalent in schema.json at
    all -- a naive rebuild would silently discard this for every one
    of the ~1,638 entries that currently have it

This is the same logic that was previously run as a python3 -c one-liner
(documented in project_context.pdf) -- pulled into a standalone script so
it's not fragile to shell quoting.
"""

import json
import re

with open("schema.json", "r", encoding="utf-8") as f:
    schema = json.load(f)

with open("data.js", "r", encoding="utf-8") as f:
    existing = f.read()

# --- Parse the CURRENT data.js so we can carry forward what schema.json
#     doesn't know about: MIMIC-IV's schema-less entries, and every
#     entry's 'linkage' field. ---
m = re.search(r"const DATASETS = (\[.*?\]);", existing, re.DOTALL)
if not m:
    raise RuntimeError("Could not find 'const DATASETS = [...]' in the "
                        "existing data.js -- aborting rather than risk "
                        "silently producing a broken file.")
existing_datasets = json.loads(m.group(1))

existing_by_id = {d["id"]: d for d in existing_datasets}
mimic_iv_entries = [d for d in existing_datasets if d.get("source") == "MIMIC-IV"]

print(f"Existing data.js: {len(existing_datasets)} entries "
      f"({len(mimic_iv_entries)} MIMIC-IV entries with no schema.json "
      f"equivalent -- these will be carried forward as-is)")

linkage_count = sum(1 for d in existing_datasets if d.get("linkage"))
print(f"Existing entries with a 'linkage' field: {linkage_count} "
      f"(will be preserved for any id that still exists)")

# --- Build the schema.json-derived entries, carrying forward 'linkage'
#     for any id that already had one. ---
datasets = []
for k, v in schema.items():
    entry = {
        "id": k,
        "name": v.get("name", k),
        "desc": v.get("desc", ""),
        "source": v.get("source", ""),
        "subtypes": v.get("subtypes", []),
        "tasks": v.get("tasks", []),
        "last_updated": v.get("last_updated", ""),
        "docUrl": v.get("url", ""),
    }
    old = existing_by_id.get(k)
    if old and old.get("linkage"):
        entry["linkage"] = old["linkage"]
    datasets.append(entry)

# --- Append MIMIC-IV's entries unchanged, since schema.json has no
#     record of them at all. ---
datasets.extend(mimic_iv_entries)

new_linkage_count = sum(1 for d in datasets if d.get("linkage"))
print(f"\nNew data.js: {len(datasets)} entries "
      f"({new_linkage_count} with 'linkage' preserved, "
      f"{len(mimic_iv_entries)} MIMIC-IV entries carried forward)")

idx = existing.find("const SUBTYPE_TAG")
tags = existing[idx:] if idx != -1 else ""

with open("data.js", "w", encoding="utf-8") as f:
    f.write("const DATASETS = ")
    json.dump(datasets, f, indent=2, ensure_ascii=False)
    f.write(";\n\n" + tags)

print(f"\nWrote data.js with {len(datasets)} total datasets.")
